image:
- Visual Studio 2017
- Ubuntu
version: 1.6.0.{build}
configuration: Release
skip_branch_with_pr: true
install:
- git submodule update --init --recursive
assembly_info:
  patch: true
  file: AssemblyInfoCommon.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: |
    dotnet build PT.SourceStats.sln -c Release

    if ($isWindows) {

        dotnet publish PT.SourceStats.Cli/PT.SourceStats.Cli.csproj -c Release -o ../bin/net462 -f net462

    }
test_script:
- ps: |
    cd PT.SourceStats.Tests/bin/Release/netcoreapp2.0

    dotnet vstest PT.SourceStats.Tests.dll --logger:nunit

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID", (Resolve-Path ./TestResults/TestResults.xml))

    cd ../../../..
after_test:
- ps: |
    if ($isWindows) {

        cd bin/net462

        7z a PT.PM.SourceStats-netcoreapp2.0-$env:APPVEYOR_BUILD_VERSION.zip *.exe *.dll *.config *.json runtimes

        Push-AppveyorArtifact PT.PM.SourceStats-netcoreapp2.0-$env:APPVEYOR_BUILD_VERSION.zip

    }
